### ISSUE TITLE
make an algorithm applying cesar encryption

### ISSUE THREAD

**Issue by Juandavid716** [themonkeyhacker/Hacktober-Challenges#12]

**Comment by jigmetnamgyal** [comment]
Can you assign me this , Thank you

**Comment by Juandavid716** [comment]
only create a folder with the issue's name and do PR :)

**Comment by mariaachim** [comment]
just added my own code for this issue, but you can still do it if you wish to do so, just add your script to the caesar-cipher directory :))

**Comment by cypher-adi** [comment]
Just implemented the Caesar using Javascript.
Please do review the PR. #57
