### ISSUE TITLE
Fizz Buzz Game

### ISSUE THREAD

**Issue by AyushRajSharma** [themonkeyhacker/Hacktober-Challenges#88]
FIZZ BUZZ GAME
Write a short program that prints each number from 1 to n on a new line.(n is number given by user) 

For each multiple of 3, print "Fizz" instead of the number. 

For each multiple of 5, print "Buzz" instead of the number. 

For numbers which are multiples of both 3 and 5, print "FizzBuzz" instead of the number.

**Comment by AyushRajSharma** [comment]
#10

**Comment by Divyanshu-info** [comment]
Can i make this game in C++
